Show a separate error for mistyped arguments

diff --git a/birb b/birb
--- a/birb
+++ b/birb
@@ -1193,6 +1193,11 @@ while test $# -gt 0; do
 			fakeroot_repair
 			;;
 
+		-*)
+			echo "Invalid argument: $1"
+			exit 1
+			;;
+
 		*)
 			echo "Package $1 does not exist"
 			exit 1
