Avoid issues with missing seed files

diff --git a/birb b/birb
--- a/birb
+++ b/birb
@@ -20,6 +20,16 @@ file
 gcc
 "
 
+println()
+{
+	case $1 in
+		*) echo -e "\e[32m=> \e[0m$@" ;;
+		ERROR) echo -e "\e[31mERROR: $2\e[0m" ;;
+		WARNING) echo -e "\e[35mWARNING: $2\e[0m" ;;
+	esac
+}
+
+
 print_help()
 {
 	echo "Usage: birb [OPTIONS...] [ARGUMENTS...] [PACKAGE(s)...]"
@@ -58,16 +68,8 @@ checksum_check()
 
 source_pkg_seed()
 {
+	[ ! -f $REPO_DIR/$1/seed.sh ] && println ERROR "The package [$1] is possibly corrupted. Resyncing packages might fix this" && return 1
 	source $REPO_DIR/$1/seed.sh
-}
-
-println()
-{
-	case $1 in
-		*) echo -e "\e[32m=> \e[0m$@" ;;
-		ERROR) echo -e "\e[31mERROR: $2\e[0m" ;;
-		WARNING) echo -e "\e[35mWARNING: $2\e[0m" ;;
-	esac
 }
 
 # Download a tarball for the given package using wget
@@ -75,7 +77,7 @@ println()
 download_src()
 {
 	# Source the package variables
-	source_pkg_seed $1
+	source_pkg_seed $1 || return 1
 
 	# Make sure that the package has a checksum
 	[ -z "$CHECKSUM" ] && println ERROR "Package [$NAME] doesn't define a checksum! The package won't be downloaded." && return 1
