Add support for 32bit library building with a flag + extra error checking

diff --git a/birb b/birb
--- a/birb
+++ b/birb
@@ -117,10 +117,27 @@ install_package()
 
 	set -e
 
+	# Reset all package variables in-case some package has omitted
+	# a variable or two
+	NAME=""
+	DESC=""
+	VERSION=""
+	SOURCE=""
+	CHECKSUM=""
+	DEPS=""
+	FLAGS=""
+
 	# Source the package variables and functions
 	source_pkg_seed $PACKAGE_NAME
 
-	# TODO: Extract the files to /tmp instead of distfiles
+	# Make sure that the package has set all of the required variables
+	[ -z "$NAME" ] 		&& echo "Encountered a package with a missing name! Aborting the mission..." && exit 1
+	[ -z "$SOURCE" ] 	&& echo "Encountered a package without a tarball source! Aborting the mission..." && exit 1
+	[ -z "$CHECKSUM" ] 	&& echo "Encountered a package without a checksum! Aborting the mission..." && exit 1
+
+	# Check if the package wants to also build 32bit libraries
+	ENABLE_32BIT="$(echo "$FLAGS" | grep -o "32bit")"
+
 	# Extract the package sources and do any required setup
 	TEMPORARY_BUILD_DIR="/tmp/birb_package_build"
 	rm -rf $TEMPORARY_BUILD_DIR
@@ -137,6 +154,21 @@ install_package()
 	echo "=> Installing the package"
 	prepare_fakeroot $FAKEROOT/$PACKAGE_NAME
 	_install
+
+	if [ -n "$ENABLE_32BIT" ]
+	then
+		echo "=> Building the package with 32-bit libraries"
+		_build32
+
+		echo "=> Installing 32-bit libraries"
+		_install32
+
+		echo "=> Building the package with x32-bit libraries"
+		_buildx32
+
+		echo "=> Installing x32-bit libraries"
+		_installx32
+	fi
 
 	# Clean things up
 	echo "=> Cleaning up"
