Fix an arg error + quit the script on error

diff --git a/birb b/birb
--- a/birb
+++ b/birb
@@ -102,7 +102,9 @@ install_package()
 	fi
 
 	# Attempt to download the package
-	[ $(download_src $PACKAGE_NAME) -eq 1 ] && echo "Error during downloading [$PACKAGE_NAME]. Aborting the mission..." && exit 1
+	[ $(download_src "$PACKAGE_NAME") -eq 1 ] && echo "Error during downloading [$PACKAGE_NAME]. Aborting the mission..." && exit 1
+
+	set -e
 
 	# Source the package variables and functions
 	source_pkg_seed $PACKAGE_NAME
@@ -134,6 +136,7 @@ install_package()
 	echo "$PACKAGE_NAME" >> $NEST
 
 	echo "$PACKAGE_NAME installation finished"
+	set +e
 }
 
 # Check if the first argument is a valid package name
