Print error when using an invalid source branch arg

diff --git a/birb b/birb
--- a/birb
+++ b/birb
@@ -1317,6 +1317,11 @@ while test $# -gt 0; do
 					echo "Switching to the unstable development branch..."
 					git checkout dev
 					;;
+
+				*)
+					println ERROR "Invalid argument: $1"
+					exit 1
+					;;
 			esac
 			shift
 			;;
